source "https://rubygems.org"

gem "jekyll", "~> 3.9"
gem "webrick", "~> 1.8"
gem "ffi", "~> 1.16.0"
gem "logger", "~> 1.6"
gem "base64", "~> 0.2"
gem "bigdecimal", "~> 3.1"
gem "csv", "~> 3.3"
gem "mutex_m", "~> 0.2"
gem "kramdown-parser-gfm"
